"""
Workday JSON API job poller.

Many large companies (NVIDIA, Tesla, Apple, Salesforce, etc.) use Workday
as their ATS. Workday exposes a stable, unauthenticated JSON endpoint on
every tenant:

    POST https://{tenant}.wd5.myworkdayjobs.com/wday/cxs/{tenant}/{board}/jobs
    Body: {"limit": 20, "offset": 0, "searchText": "data scientist"}

This is far more reliable than Playwright scraping — returns structured JSON,
no browser automation, no HTML parsing.

For CSRF-protected tenants (Tesla, Salesforce, Apple, AMD), the CSRF token is
generated by JavaScript at runtime and cannot be extracted from static HTML.
We use Playwright to load the careers page, then make the API call from
within the browser context where CSRF cookies are already set up.

Job URL format:
    https://{tenant}.wd5.myworkdayjobs.com/en-US/{board}/job/{externalPath}
"""

import json
import logging
import re
import time
import uuid
from typing import Optional

import requests

from config import ROLE_KEYWORDS, EXCLUDE_KEYWORDS, WORKDAY_API_COMPANIES, WORKDAY_CSRF_COMPANIES

logger = logging.getLogger(__name__)

API_URL_TEMPLATE = (
    "https://{tenant}.wd5.myworkdayjobs.com/wday/cxs/{tenant}/{board}/jobs"
)
JOB_URL_TEMPLATE = (
    "https://{tenant}.wd5.myworkdayjobs.com/en-US/{board}/job/{path}"
)

CAREERS_PAGE_TEMPLATE = (
    "https://{tenant}.wd5.myworkdayjobs.com/en-US/{board}"
)

REQUEST_TIMEOUT = 20
RESULTS_PER_COMPANY = 20

HEADERS = {
    "Content-Type": "application/json",
    "User-Agent": (
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept": "application/json",
}


def _is_relevant(title: str) -> bool:
    t = title.lower()
    if not any(kw in t for kw in ROLE_KEYWORDS):
        return False
    if any(kw in t for kw in EXCLUDE_KEYWORDS):
        return False
    return True


def _parse_postings(data: dict, tenant: str, board: str, company_name: str) -> list[dict]:
    """Convert raw Workday API response into job dicts."""
    postings = data.get("jobPostings", [])
    jobs = []
    for posting in postings:
        title = (posting.get("title") or "").strip()
        external_path = (posting.get("externalPath") or "").strip("/")
        location = posting.get("locationsText") or posting.get("primaryLocation", "")
        posted = posting.get("postedOn", "")

        if re.match(r"^\d+\s+location", (location or "").lower()):
            path_parts = external_path.split("/")
            if len(path_parts) >= 2:
                segs = path_parts[1].split("-")
                if len(segs) >= 3:
                    location = f"{segs[0]}, {segs[1]}, {' '.join(segs[2:])}"
                elif len(segs) == 2:
                    location = f"{segs[0]}, {segs[1]}"
                else:
                    location = segs[0]

        bullet_fields = posting.get("jobDescription", {})
        description = (bullet_fields.get("items") or [{}])[0].get("text", "") if bullet_fields else ""

        if not title or not external_path or not _is_relevant(title):
            continue

        jobs.append({
            "title": title,
            "company": company_name,
            "url": JOB_URL_TEMPLATE.format(tenant=tenant, board=board, path=external_path),
            "location": location,
            "jd_text": description[:3000] if description else "",
            "source": "workday",
            "posted_date": posted,
        })
    return jobs


def _fetch_company_jobs(
    tenant: str,
    board: str,
    company_name: str,
    search_text: str,
) -> list[dict]:
    """Fetch jobs for one Workday company via direct JSON API (no CSRF needed)."""
    url = API_URL_TEMPLATE.format(tenant=tenant, board=board)
    payload = {"limit": RESULTS_PER_COMPANY, "offset": 0, "searchText": search_text}

    for attempt in range(3):
        try:
            resp = requests.post(url, json=payload, headers=HEADERS, timeout=REQUEST_TIMEOUT)
            if resp.status_code == 404:
                logger.warning("Workday: board not found for %s", company_name)
                return []
            if resp.status_code in (403, 429):
                logger.warning("Workday: blocked (%d) for %s", resp.status_code, company_name)
                return []
            resp.raise_for_status()
            return _parse_postings(resp.json(), tenant, board, company_name)
        except requests.RequestException as e:
            if attempt < 2:
                time.sleep(2 ** attempt)
                logger.warning("Workday attempt %d failed for %s: %s", attempt + 1, company_name, e)
            else:
                logger.error("Workday: all retries failed for %s: %s", company_name, e)
    return []


def _fetch_company_jobs_playwright(
    tenant: str,
    board: str,
    company_name: str,
    search_text: str,
) -> list[dict]:
    """
    Fetch jobs from CSRF-protected Workday tenants using Playwright.

    Strategy: load the careers page as a real browser (headless Chromium) so
    the session cookies and CSRF token are automatically set up, then call the
    jobs API from within that browser context via fetch(). The browser handles
    all CSRF headers transparently.

    Requires: playwright install chromium  (run once after pip install)
    """
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        logger.warning("Playwright not installed — skipping CSRF tenant %s", company_name)
        return []

    careers_url = CAREERS_PAGE_TEMPLATE.format(tenant=tenant, board=board)
    api_url     = API_URL_TEMPLATE.format(tenant=tenant, board=board)
    payload     = json.dumps({"limit": RESULTS_PER_COMPANY, "offset": 0, "searchText": search_text})

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            ctx = browser.new_context(
                user_agent=HEADERS["User-Agent"],
                extra_http_headers={"Accept-Language": "en-US,en;q=0.9"},
            )
            page = ctx.new_page()

            logger.info("Workday Playwright: loading %s for %s", careers_url, company_name)
            page.goto(careers_url, wait_until="networkidle", timeout=45000)

            # Make the API call from inside the browser — CSRF cookies are already set
            result = page.evaluate(f"""
                async () => {{
                    const r = await fetch("{api_url}", {{
                        method: "POST",
                        headers: {{"Content-Type": "application/json", "Accept": "application/json"}},
                        credentials: "include",
                        body: {json.dumps(payload)}
                    }});
                    if (!r.ok) return null;
                    return r.json();
                }}
            """)
            browser.close()

        if not result:
            logger.warning("Workday Playwright: empty response for %s", company_name)
            return []
        return _parse_postings(result, tenant, board, company_name)

    except Exception as e:
        logger.warning("Workday Playwright failed for %s: %s", company_name, e)
        return []


def fetch_workday_jobs(
    companies: Optional[dict] = None,
    csrf_companies: Optional[dict] = None,
) -> list[dict]:
    """Fetch jobs from all configured Workday companies."""
    if companies is None:
        companies = WORKDAY_API_COMPANIES
    if csrf_companies is None:
        csrf_companies = WORKDAY_CSRF_COMPANIES

    all_jobs: list[dict] = []

    # Standard tenants — direct JSON API
    for tenant, cfg in companies.items():
        logger.info("Workday: polling %s (tenant: %s)", cfg["name"], tenant)
        try:
            jobs = _fetch_company_jobs(tenant, cfg["board"], cfg["name"], cfg.get("search", "data scientist"))
            logger.info("Workday %s: %d relevant jobs", cfg["name"], len(jobs))
            all_jobs.extend(jobs)
        except Exception as e:
            logger.error("Workday: %s failed: %s", cfg["name"], e)
        time.sleep(0.5)

    # CSRF-protected tenants — Playwright browser
    for tenant, cfg in csrf_companies.items():
        logger.info("Workday CSRF: polling %s (tenant: %s)", cfg["name"], tenant)
        try:
            jobs = _fetch_company_jobs_playwright(tenant, cfg["board"], cfg["name"], cfg.get("search", "data scientist"))
            logger.info("Workday CSRF %s: %d relevant jobs", cfg["name"], len(jobs))
            all_jobs.extend(jobs)
        except Exception as e:
            logger.error("Workday CSRF: %s failed: %s", cfg["name"], e)
        time.sleep(1.0)

    logger.info("Workday total: %d jobs", len(all_jobs))
    return all_jobs

