"""
Greenhouse application question classifier.

For every question on a Greenhouse form this module decides:
  PROFILE  → answer from profile.yaml (visa, salary, start date, etc.)
  EEO      → answer from profile.yaml [eeo] section
  CANNED   → verbatim answer from profile.yaml [canned_answers]
  GEMINI   → answer generated by Gemini Flash using resume + JD
  PENDING  → cannot answer confidently; save for user to fill in dashboard

Returns a list of processed question dicts, each with:
  field_name, label, field_type, options, required, answer, answered_by
"""

import os
import re
import logging
from datetime import date
from pathlib import Path
from typing import Optional

import google.generativeai as genai

logger = logging.getLogger(__name__)

# Fields where the agent must ONLY answer from profile.yaml — never LLM.
_SENSITIVE_LABELS = re.compile(
    r"visa|sponsor|work auth|authoriz|immigration|h[1-4][ab]?\b|opt\b|cpt\b|ead\b|"
    r"gender|sex\b|race|ethnic|hispanic|latino|veteran|military|disabilit|"
    r"citizenship|nationality|clearance",
    re.I,
)

# Salary range extractor: captures low and high bound from JD text
_SALARY_RANGE_RE = re.compile(
    r"\$\s*(\d{2,3}(?:,\d{3})*(?:\.\d+)?)\s*[kK]?\s*(?:–|-|to)\s*\$?\s*"
    r"(\d{2,3}(?:,\d{3})*(?:\.\d+)?)\s*[kK]?",
    re.I,
)

_PROFILE_PATH = Path(__file__).resolve().parent.parent / "profile.yaml"

# ── Standard Greenhouse fields already handled by _profile() in auto_apply ───

_STANDARD_LABELS = {
    "first name", "last name", "email address", "email", "phone", "phone number",
    "resume", "resume/cv", "cover letter", "linkedin profile", "linkedin profile url",
    "website", "personal website", "portfolio", "location", "city", "state", "country",
    "address", "zip code", "postal code",
}

# ── Keyword patterns → profile.yaml key path ─────────────────────────────────

_PROFILE_PATTERNS: list[tuple[re.Pattern, str, str]] = [
    # (regex, top-level section, key within section)
    (re.compile(r"visa|sponsorship|sponsor|work auth|authoriz|work permit|immigration|h[1-4][ab]?\b|opt\b|cpt\b|ead\b", re.I),
     "work_authorization", "needs_sponsorship"),
    (re.compile(r"authorized.{0,20}work|legally.{0,20}work|eligible.{0,20}work|permission.{0,20}work", re.I),
     "work_authorization", "authorized_us"),
    (re.compile(r"citizenship|citizen|nationality|permanent resident|green card", re.I),
     "work_authorization", "citizenship"),
    (re.compile(r"salary|compensation|pay\b|expected pay|remuneration", re.I),
     "compensation", "expected_salary_usd"),
    (re.compile(r"total comp|total compensation|equity|stock|bonus", re.I),
     "compensation", "expected_total_comp"),
    (re.compile(r"start date|earliest.{0,15}start|when.{0,15}start|available.{0,15}start", re.I),
     "availability", "earliest_start_date"),
    (re.compile(r"notice period|notice|current notice", re.I),
     "availability", "notice_period"),
    (re.compile(r"relocat", re.I),
     "availability", "willing_to_relocate"),
    (re.compile(r"remote|hybrid|on.?site|in.?office|work.{0,10}arrangement|work.{0,10}mode", re.I),
     "availability", "preferred_work_mode"),
    (re.compile(r"degree|bachelor|master|phd|doctorate|education level|highest.{0,10}education", re.I),
     "background", "highest_degree"),
    (re.compile(r"years.{0,15}experience|experience.{0,15}years|how many years", re.I),
     "background", "years_total_experience"),
    (re.compile(r"security clearance|clearance level|government clearance", re.I),
     "background", "us_security_clearance"),
    (re.compile(r"background check|drug test|criminal", re.I),
     "background", "willing_to_undergo_background_check"),
]

_EEO_PATTERNS = re.compile(
    r"gender|sex\b|female|male|non.?binary|race|ethnic|minority|hispanic|latino|asian|"
    r"pacific islander|native american|veteran|military|armed forces|disabilit|handicap|"
    r"equal employment|eeo|diversity",
    re.I,
)

_CANNED_PATTERNS: list[tuple[re.Pattern, str]] = [
    (re.compile(r"how did you hear|how.{0,10}find.{0,10}(this|role|position|us)|"
                r"referred|referral|source.{0,10}(role|position|this)", re.I),
     "how_did_you_hear"),
    (re.compile(r"why.{0,20}(leaving|leave|left).{0,20}(current|previous|last)|"
                r"reason.{0,15}leaving", re.I),
     "why_leaving"),
]

_MOTIVATIONAL_RE = re.compile(
    r"why.{0,30}(join|apply|want|interested|chose|choose|this role|this company|us\b)|"
    r"what.{0,30}(interest|excit|passion|attract|draw|motivat)|"
    r"tell us (about|why)|describe (yourself|your|why)|"
    r"what makes you|what (would you|will you|can you) (bring|contribut|offer)|"
    r"career goal|strengths?|why (are|do) you|"
    r"what.{0,20}(qualif|fit|suited|good fit)|"
    r"brief(ly)? (describe|explain|tell)|"
    r"how.{0,20}(experience|background|skill).{0,20}(relevant|apply|help|fit)",
    re.I,
)


# ── Profile loader ────────────────────────────────────────────────────────────

def _load_profile() -> dict:
    try:
        import yaml
        if _PROFILE_PATH.exists():
            with open(_PROFILE_PATH) as f:
                return yaml.safe_load(f) or {}
    except Exception as e:
        logger.warning("Could not load profile.yaml: %s", e)
    return {}


def _get_profile_value(profile: dict, section: str, key: str) -> Optional[str]:
    val = profile.get(section, {}).get(key)
    return str(val).strip() if val not in (None, "") else None


# ── Option matching ───────────────────────────────────────────────────────────

def _match_option(answer: str, options: list[dict]) -> Optional[str]:
    """
    Given a profile answer string (e.g. "Yes") and a list of Greenhouse option
    dicts [{value, label}], return the option value whose label best matches.
    Returns the answer string unchanged if no options provided.
    """
    if not options:
        return answer
    # Exact case-insensitive label match
    for opt in options:
        if opt.get("label", "").strip().lower() == answer.strip().lower():
            return opt.get("label", opt.get("value", ""))
    # Partial: answer starts with or is contained in label
    for opt in options:
        lbl = opt.get("label", "").lower()
        if answer.lower() in lbl or lbl.startswith(answer.lower()):
            return opt.get("label", opt.get("value", ""))
    # Fallback: first option for Yes/No when answer is truthy yes-like
    if answer.lower() in ("yes", "true", "1") and options:
        # pick option whose label looks like "Yes"
        for opt in options:
            if opt.get("label", "").lower().startswith("yes"):
                return opt.get("label", opt.get("value", ""))
    if answer.lower() in ("no", "false", "0") and options:
        for opt in options:
            if opt.get("label", "").lower().startswith("no"):
                return opt.get("label", opt.get("value", ""))
    return None  # couldn't match → pending


# ── EEO answer resolver ───────────────────────────────────────────────────────

def _eeo_answer(label: str, profile: dict, options: list[dict]) -> Optional[str]:
    eeo = profile.get("eeo", {})
    lc = label.lower()
    if "gender" in lc or "sex" in lc:
        raw = eeo.get("gender", "Prefer not to answer")
    elif "hispanic" in lc or "latino" in lc:
        raw = eeo.get("hispanic_latino", "No")
    elif "race" in lc or "ethnic" in lc:
        raw = eeo.get("race_ethnicity", "Prefer not to answer")
    elif "veteran" in lc or "military" in lc:
        raw = eeo.get("veteran_status", "I am not a protected veteran")
    elif "disabilit" in lc:
        raw = eeo.get("disability", "No, I do not have a disability and have not had one in the past")
    else:
        raw = "Prefer not to answer"
    if not raw:
        raw = "Prefer not to answer"
    matched = _match_option(raw, options)
    return matched if matched else raw


def _extract_salary_from_jd(jd_text: str) -> Optional[str]:
    """Extract lower bound of salary range from JD text. Returns as plain number string."""
    m = _SALARY_RANGE_RE.search(jd_text or "")
    if not m:
        return None
    low = m.group(1).replace(",", "")
    # Handle shorthand like 120k → 120000
    if "k" in m.group(0).lower():
        try:
            low = str(int(float(low) * 1000)) if float(low) < 1000 else low
        except ValueError:
            pass
    return low


def _start_date_for_field(field_type: str) -> str:
    """Return an appropriate start date value based on the field input type."""
    today = date.today()
    if field_type == "date":
        return today.isoformat()           # YYYY-MM-DD
    if field_type in ("input_text", "textarea"):
        return "Immediate"
    return "Immediate"


# ── Company info fetcher ──────────────────────────────────────────────────────

def _fetch_company_about(company_name: str, job_url: str) -> str:
    """
    Fetch a brief description of the company from their website.
    Tries /about page first, falls back to homepage. Returns up to 800 chars.
    Times out quickly so it never blocks the pipeline.
    """
    import requests
    from bs4 import BeautifulSoup

    slug = re.sub(r"[^a-z0-9]", "", company_name.lower())

    # Build candidate URLs
    candidates = [
        f"https://www.{slug}.com/about",
        f"https://{slug}.com/about",
        f"https://www.{slug}.com",
    ]
    # Also try to extract domain from job URL (e.g. careers.coupang.com → coupang.com)
    m = re.search(r"(?:careers|jobs)\.([^./]+\.[a-z]{2,3})", job_url)
    if m:
        domain = m.group(1)
        candidates.insert(0, f"https://{domain}/about")
        candidates.insert(0, f"https://www.{domain}/about")

    headers = {"User-Agent": "Mozilla/5.0 (compatible; JobAgent/1.0)"}
    for url in candidates[:4]:
        try:
            resp = requests.get(url, timeout=5, headers=headers)
            if resp.status_code != 200:
                continue
            soup = BeautifulSoup(resp.text, "html.parser")
            for tag in soup(["script", "style", "nav", "footer", "header"]):
                tag.decompose()
            text = " ".join(soup.get_text(separator=" ", strip=True).split())
            if len(text) > 100:
                return text[:800]
        except Exception:
            continue
    return ""


# ── Gemini batch answer for motivational questions ────────────────────────────

_MOTIVATIONAL_SYSTEM = (
    "You answer job application questions. For each numbered question, "
    "respond in 2–3 sentences. Be specific, genuine, and grounded in the "
    "provided resume and job description. Do not fabricate facts. "
    "Reply with only the numbered answers, one per line, in the same order. "
    "Format: '1. [answer]\\n2. [answer]' etc. No preamble, no sign-off."
)


def _gemini_model():
    genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
    return genai.GenerativeModel("gemini-2.0-flash", system_instruction=_MOTIVATIONAL_SYSTEM)


def _claude_answer_batch(
    labels: list[str],
    jd_text: str,
    resume_text: str,
    client=None,
    company_name: str = "",
    company_about: str = "",
) -> dict[str, str]:
    """
    Answer all motivational questions in a single Gemini Flash call.
    Returns a dict mapping each label to its answer.
    """
    if not labels:
        return {}

    try:
        company_section = (
            f"Company overview (from their website):\n{company_about[:600]}\n\n"
            if company_about else ""
        )

        numbered = "\n".join(f"{i+1}. {q}" for i, q in enumerate(labels))

        user_text = (
            f"Applicant resume:\n{resume_text[:1800]}\n\n"
            f"{company_section}"
            f"Job description (excerpt):\n{jd_text[:1200]}\n\n"
            f"Answer each of the following application questions:\n{numbered}"
        )

        model = _gemini_model()
        response = model.generate_content(user_text)
        raw = response.text.strip()

        # Parse numbered answers back to labels
        answers: dict[str, str] = {}
        lines = [l.strip() for l in raw.splitlines() if l.strip()]
        for line in lines:
            m = re.match(r"^(\d+)\.\s*(.*)", line)
            if m:
                idx = int(m.group(1)) - 1
                if 0 <= idx < len(labels):
                    answers[labels[idx]] = m.group(2).strip()

        # Fallback: if parsing failed but we only had one question, use the whole text
        if not answers and len(labels) == 1:
            answers[labels[0]] = raw

        return answers

    except Exception as e:
        logger.warning("Gemini batch answer failed: %s", e)
        return {}


# ── Main classifier ───────────────────────────────────────────────────────────

def classify_and_answer(
    questions: list[dict],
    jd_text: str = "",
    resume_text: str = "",
    client=None,
    job_url: str = "",
    company_name: str = "",
) -> list[dict]:
    """
    Classify every Greenhouse question and provide an answer where possible.

    Args:
        questions:    Raw questions list from Greenhouse API.
        jd_text:      Job description text (for Gemini motivational answers).
        resume_text:  Applicant resume text (for Gemini motivational answers).
        client:       Unused (kept for backward compatibility).

    Returns:
        List of dicts with keys:
          field_name, label, field_type, options, required, answer, answered_by
        answer is None for questions that need user input (shown in dashboard).
    """
    profile = _load_profile()
    results = []

    # Fetch company info once for use in all motivational answers
    company_about = ""
    if company_name:
        logger.info("Fetching company info for: %s", company_name)
        company_about = _fetch_company_about(company_name, job_url)
        if company_about:
            logger.info("Got %d chars of company info for %s", len(company_about), company_name)
        else:
            logger.info("No company info found for %s — using JD only", company_name)

    # First pass: classify all questions without calling LLM
    pending_claude: list[str] = []  # motivational question labels for batch call

    for q in questions:
        label_raw = q.get("label", "")
        label_lc  = label_raw.lower().strip()
        q_required = bool(q.get("required"))

        if label_lc in _STANDARD_LABELS:
            continue

        for field in q.get("fields", []):
            field_type = field.get("type", "input_text")

            if field_type in ("input_file", "attachment"):
                continue

            if (
                _MOTIVATIONAL_RE.search(label_raw)
                and field_type in ("input_text", "textarea")
                and not _SENSITIVE_LABELS.search(label_raw)
                and not _EEO_PATTERNS.search(label_raw)
                and not _classify_profile(label_raw)
                and not _classify_canned(label_raw)
                and (jd_text or resume_text)
                and label_raw not in pending_claude
            ):
                pending_claude.append(label_raw)

    # Single batched Gemini call for all motivational questions
    claude_answers: dict[str, str] = {}
    if pending_claude:
        logger.info("Sending %d motivational questions to Gemini in one call", len(pending_claude))
        claude_answers = _claude_answer_batch(
            pending_claude, jd_text, resume_text, client,
            company_name=company_name,
            company_about=company_about,
        )

    # Second pass: build results using pre-computed Gemini answers
    for q in questions:
        label_raw = q.get("label", "")
        label_lc  = label_raw.lower().strip()
        q_required = bool(q.get("required"))

        if label_lc in _STANDARD_LABELS:
            continue

        for field in q.get("fields", []):
            field_type = field.get("type", "input_text")
            field_name = field.get("name") or str(q.get("id", ""))
            f_required = bool(field.get("required", q_required))
            options    = field.get("values") or []

            if field_type in ("input_file", "attachment"):
                continue

            answer      : Optional[str] = None
            answered_by : Optional[str] = None

            # ── EEO fields ─────────────────────────────────────────────────
            if field_type.startswith("eeo_") or _EEO_PATTERNS.search(label_raw):
                answer      = _eeo_answer(label_raw, profile, options)
                answered_by = "agent_eeo"

            # ── Profile / factual fields ────────────────────────────────────
            elif _profile_match := _classify_profile(label_raw):
                section, key = _profile_match

                if section == "compensation":
                    if not f_required:
                        answer      = ""
                        answered_by = "agent_skip_optional"
                    else:
                        salary = _extract_salary_from_jd(jd_text)
                        if salary:
                            matched = _match_option(salary, options)
                            answer      = matched if matched is not None else salary
                            answered_by = "agent_jd_salary"

                elif section == "availability" and key == "earliest_start_date":
                    answer      = _start_date_for_field(field_type)
                    answered_by = "agent_profile"

                else:
                    raw = _get_profile_value(profile, section, key)
                    if raw:
                        matched = _match_option(raw, options)
                        if matched is not None:
                            answer      = matched
                            answered_by = "agent_profile"

            # ── Canned answers ──────────────────────────────────────────────
            elif canned_key := _classify_canned(label_raw):
                raw = (profile.get("canned_answers") or {}).get(canned_key)
                if raw:
                    matched = _match_option(str(raw), options)
                    answer      = matched if matched is not None else str(raw)
                    answered_by = "agent_canned"

            # ── Motivational / fit questions — use pre-fetched batch answers ─
            elif (
                _MOTIVATIONAL_RE.search(label_raw)
                and field_type in ("input_text", "textarea")
                and not _SENSITIVE_LABELS.search(label_raw)
            ):
                answer = claude_answers.get(label_raw)
                if answer:
                    answered_by = "agent_claude"

            results.append({
                "field_name":  field_name,
                "label":       label_raw,
                "field_type":  field_type,
                "options":     options if options else None,
                "required":    f_required,
                "answer":      answer,
                "answered_by": answered_by,
                "job_url":     job_url if answer is None else "",
            })

    return results


def _classify_profile(label: str) -> Optional[tuple[str, str]]:
    for pattern, section, key in _PROFILE_PATTERNS:
        if pattern.search(label):
            return section, key
    return None


def _classify_canned(label: str) -> Optional[str]:
    for pattern, key in _CANNED_PATTERNS:
        if pattern.search(label):
            return key
    return None
