"""
Greenhouse application question classifier.

For every question on a Greenhouse form this module decides:
  PROFILE  → answer from profile.yaml (visa, salary, start date, etc.)
  EEO      → answer from profile.yaml [eeo] section
  CANNED   → verbatim answer from profile.yaml [canned_answers]
  CLAUDE   → answer generated by Claude Haiku using resume + JD
  PENDING  → cannot answer confidently; save for user to fill in dashboard

Returns a list of processed question dicts, each with:
  field_name, label, field_type, options, required, answer, answered_by
"""

import re
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

_PROFILE_PATH = Path(__file__).resolve().parent.parent / "profile.yaml"

# ── Standard Greenhouse fields already handled by _profile() in auto_apply ───

_STANDARD_LABELS = {
    "first name", "last name", "email address", "email", "phone", "phone number",
    "resume", "resume/cv", "cover letter", "linkedin profile", "linkedin profile url",
    "website", "personal website", "portfolio", "location", "city", "state", "country",
    "address", "zip code", "postal code",
}

# ── Keyword patterns → profile.yaml key path ─────────────────────────────────

_PROFILE_PATTERNS: list[tuple[re.Pattern, str, str]] = [
    # (regex, top-level section, key within section)
    (re.compile(r"visa|sponsorship|sponsor|work auth|authoriz|work permit|immigration|h[1-4][ab]?\b|opt\b|cpt\b|ead\b", re.I),
     "work_authorization", "needs_sponsorship"),
    (re.compile(r"authorized.{0,20}work|legally.{0,20}work|eligible.{0,20}work|permission.{0,20}work", re.I),
     "work_authorization", "authorized_us"),
    (re.compile(r"citizenship|citizen|nationality|permanent resident|green card", re.I),
     "work_authorization", "citizenship"),
    (re.compile(r"salary|compensation|pay\b|expected pay|remuneration", re.I),
     "compensation", "expected_salary_usd"),
    (re.compile(r"total comp|total compensation|equity|stock|bonus", re.I),
     "compensation", "expected_total_comp"),
    (re.compile(r"start date|earliest.{0,15}start|when.{0,15}start|available.{0,15}start", re.I),
     "availability", "earliest_start_date"),
    (re.compile(r"notice period|notice|current notice", re.I),
     "availability", "notice_period"),
    (re.compile(r"relocat", re.I),
     "availability", "willing_to_relocate"),
    (re.compile(r"remote|hybrid|on.?site|in.?office|work.{0,10}arrangement|work.{0,10}mode", re.I),
     "availability", "preferred_work_mode"),
    (re.compile(r"degree|bachelor|master|phd|doctorate|education level|highest.{0,10}education", re.I),
     "background", "highest_degree"),
    (re.compile(r"years.{0,15}experience|experience.{0,15}years|how many years", re.I),
     "background", "years_total_experience"),
    (re.compile(r"security clearance|clearance level|government clearance", re.I),
     "background", "us_security_clearance"),
    (re.compile(r"background check|drug test|criminal", re.I),
     "background", "willing_to_undergo_background_check"),
]

_EEO_PATTERNS = re.compile(
    r"gender|sex\b|female|male|non.?binary|race|ethnic|minority|hispanic|latino|asian|"
    r"pacific islander|native american|veteran|military|armed forces|disabilit|handicap|"
    r"equal employment|eeo|diversity",
    re.I,
)

_CANNED_PATTERNS: list[tuple[re.Pattern, str]] = [
    (re.compile(r"how did you hear|how.{0,10}find.{0,10}(this|role|position|us)|"
                r"referred|referral|source.{0,10}(role|position|this)", re.I),
     "how_did_you_hear"),
    (re.compile(r"why.{0,20}(leaving|leave|left).{0,20}(current|previous|last)|"
                r"reason.{0,15}leaving", re.I),
     "why_leaving"),
]

_MOTIVATIONAL_RE = re.compile(
    r"why.{0,30}(join|apply|want|interested|chose|choose|this role|this company|us\b)|"
    r"what.{0,30}(interest|excit|passion|attract|draw|motivat)|"
    r"tell us (about|why)|describe (yourself|your|why)|"
    r"what makes you|what (would you|will you|can you) (bring|contribut|offer)|"
    r"career goal|strengths?|why (are|do) you|"
    r"what.{0,20}(qualif|fit|suited|good fit)|"
    r"brief(ly)? (describe|explain|tell)|"
    r"how.{0,20}(experience|background|skill).{0,20}(relevant|apply|help|fit)",
    re.I,
)


# ── Profile loader ────────────────────────────────────────────────────────────

def _load_profile() -> dict:
    try:
        import yaml
        if _PROFILE_PATH.exists():
            with open(_PROFILE_PATH) as f:
                return yaml.safe_load(f) or {}
    except Exception as e:
        logger.warning("Could not load profile.yaml: %s", e)
    return {}


def _get_profile_value(profile: dict, section: str, key: str) -> Optional[str]:
    val = profile.get(section, {}).get(key)
    return str(val).strip() if val not in (None, "") else None


# ── Option matching ───────────────────────────────────────────────────────────

def _match_option(answer: str, options: list[dict]) -> Optional[str]:
    """
    Given a profile answer string (e.g. "Yes") and a list of Greenhouse option
    dicts [{value, label}], return the option value whose label best matches.
    Returns the answer string unchanged if no options provided.
    """
    if not options:
        return answer
    # Exact case-insensitive label match
    for opt in options:
        if opt.get("label", "").strip().lower() == answer.strip().lower():
            return opt.get("label", opt.get("value", ""))
    # Partial: answer starts with or is contained in label
    for opt in options:
        lbl = opt.get("label", "").lower()
        if answer.lower() in lbl or lbl.startswith(answer.lower()):
            return opt.get("label", opt.get("value", ""))
    # Fallback: first option for Yes/No when answer is truthy yes-like
    if answer.lower() in ("yes", "true", "1") and options:
        # pick option whose label looks like "Yes"
        for opt in options:
            if opt.get("label", "").lower().startswith("yes"):
                return opt.get("label", opt.get("value", ""))
    if answer.lower() in ("no", "false", "0") and options:
        for opt in options:
            if opt.get("label", "").lower().startswith("no"):
                return opt.get("label", opt.get("value", ""))
    return None  # couldn't match → pending


# ── EEO answer resolver ───────────────────────────────────────────────────────

def _eeo_answer(label: str, profile: dict, options: list[dict]) -> Optional[str]:
    eeo = profile.get("eeo", {})
    lc = label.lower()
    if "gender" in lc or "sex" in lc:
        raw = eeo.get("gender", "Prefer not to answer")
    elif "race" in lc or "ethnic" in lc:
        raw = eeo.get("race_ethnicity", "Prefer not to answer")
    elif "veteran" in lc or "military" in lc:
        raw = eeo.get("veteran_status", "I am not a veteran")
    elif "disabilit" in lc:
        raw = eeo.get("disability", "No, I don't have a disability")
    else:
        raw = "Prefer not to answer"
    if not raw:
        raw = "Prefer not to answer"
    matched = _match_option(raw, options)
    return matched if matched else raw


# ── Claude answer for motivational questions ──────────────────────────────────

def _claude_answer(label: str, jd_text: str, resume_text: str, client) -> Optional[str]:
    try:
        prompt = (
            f"Answer this job application question in 2–3 sentences. Be specific, "
            f"honest, and grounded in the resume and job description provided.\n\n"
            f"Question: {label}\n\n"
            f"Job description (excerpt):\n{jd_text[:1500]}\n\n"
            f"Applicant resume (excerpt):\n{resume_text[:2000]}\n\n"
            f"Answer (plain text, no preamble, no sign-off):"
        )
        msg = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=300,
            messages=[{"role": "user", "content": prompt}],
        )
        return msg.content[0].text.strip()
    except Exception as e:
        logger.warning("Claude answer failed for '%s': %s", label, e)
        return None


# ── Main classifier ───────────────────────────────────────────────────────────

def classify_and_answer(
    questions: list[dict],
    jd_text: str = "",
    resume_text: str = "",
    client=None,
) -> list[dict]:
    """
    Classify every Greenhouse question and provide an answer where possible.

    Args:
        questions:    Raw questions list from Greenhouse API.
        jd_text:      Job description text (for Claude motivational answers).
        resume_text:  Applicant resume text (for Claude motivational answers).
        client:       Anthropic client instance (optional; needed for CLAUDE type).

    Returns:
        List of dicts with keys:
          field_name, label, field_type, options, required, answer, answered_by
        answer is None for questions that need user input (shown in dashboard).
    """
    profile = _load_profile()
    results = []

    for q in questions:
        label_raw = q.get("label", "")
        label_lc  = label_raw.lower().strip()
        q_required = bool(q.get("required"))

        # Skip standard fields — handled directly in apply_greenhouse
        if label_lc in _STANDARD_LABELS:
            continue

        for field in q.get("fields", []):
            field_type = field.get("type", "input_text")
            field_name = field.get("name") or str(q.get("id", ""))
            f_required = bool(field.get("required", q_required))
            options    = field.get("values") or []  # [{value, label}]

            # Skip file attachments (resume already handled separately)
            if field_type in ("input_file", "attachment"):
                continue

            answer      : Optional[str] = None
            answered_by : Optional[str] = None

            # ── EEO fields ─────────────────────────────────────────────────
            if field_type.startswith("eeo_") or _EEO_PATTERNS.search(label_raw):
                answer      = _eeo_answer(label_raw, profile, options)
                answered_by = "agent_eeo"

            # ── Profile / factual fields ────────────────────────────────────
            elif _profile_match := _classify_profile(label_raw):
                section, key = _profile_match
                raw = _get_profile_value(profile, section, key)
                if raw:
                    matched = _match_option(raw, options)
                    if matched is not None:
                        answer      = matched
                        answered_by = "agent_profile"
                    # else: options exist but no match → pending (answer stays None)

            # ── Canned answers ──────────────────────────────────────────────
            elif canned_key := _classify_canned(label_raw):
                raw = (profile.get("canned_answers") or {}).get(canned_key)
                if raw:
                    matched = _match_option(str(raw), options)
                    answer      = matched if matched is not None else str(raw)
                    answered_by = "agent_canned"

            # ── Motivational / fit questions (text/textarea only) ───────────
            elif _MOTIVATIONAL_RE.search(label_raw) and field_type in ("input_text", "textarea"):
                if client and (jd_text or resume_text):
                    answer = _claude_answer(label_raw, jd_text, resume_text, client)
                    if answer:
                        answered_by = "agent_claude"
                # else falls through to pending

            # answer stays None → pending (shown in dashboard)

            results.append({
                "field_name":  field_name,
                "label":       label_raw,
                "field_type":  field_type,
                "options":     options if options else None,
                "required":    f_required,
                "answer":      answer,
                "answered_by": answered_by,
            })

    return results


def _classify_profile(label: str) -> Optional[tuple[str, str]]:
    for pattern, section, key in _PROFILE_PATTERNS:
        if pattern.search(label):
            return section, key
    return None


def _classify_canned(label: str) -> Optional[str]:
    for pattern, key in _CANNED_PATTERNS:
        if pattern.search(label):
            return key
    return None
